name: CICD 
on:
  push: 
    branches: 
      - master
jobs:
  build-and-deploy:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
      - name: Install Dependencies
        run: npm install
      - name: Generate Package
        run: zip -r nodejs-app-build.zip .
     
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws_secret_key: ${{secrets.AWS_ACCESS_KEY_ID}}
          application_name: 'Resume'
          environment_name: 'Resume-env'
          version_label: ${{github.sha}}
          region: us-west-2
          deployment_package: 'nodejs-app-build.zip'
        
      
    
    
